- test-MultiTimer
- test-OSC
- test-interrupt
- test-sdhc
- test-uart
- test-pdb
- test-flexcan
- test-i2c
- test-flash
- test-clockmgr
- test-edma
- KsdkPlatformLib
- test-smc
- test-adc
- test-flash-ram
- test-mcg
- test-dac
- test-wdog
- test-pit
- test-crc
- test-rtc
- test-gpio
- test-rcm
- test-dspi
